name: Pulumi Up

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read     

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: |
          npm install hackmyresume -g
      - run: | 
          html_dir="pulumi/out"
          sudo apt install xfonts-75dpi xfonts-base
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          hackmyresume build ArtemTkachuk.json TO $html_dir/index.html $html_dir/ArtemTkachuk_DevOps.pdf --theme compact
          sed -i '/<body>/a <center><h2><a href="http://cv.4ownops.click/ArtemTkachuk_DevOps.pdf">Download resume as PDF</a></h2></center>' $html_dir/index.html
          cd pulumi
          pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUMED_ROLE }}
          aws-region: eu-central-1
      - uses: pulumi/actions@v4
        with:
          work-dir: pulumi
          command: up
          stack-name: 4ownops/prod
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
